# Generated by Django 3.2.15 on 2023-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('cvv', models.CharField(max_length=20)),
                ('card_holder', models.CharField(max_length=50)),
                ('pay_sts', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
