# Generated by Django 3.2.15 on 2023-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('fac_id', models.AutoField(primary_key=True, serialize=False)),
                ('facilities', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
    ]
