# Generated by Django 3.2.15 on 2023-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rat_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
    ]
