# Generated by Django 3.2.15 on 2023-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('reminders', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
    ]
